#!/bin/bash
set -eu

# init - Bootstrap Script for Postgresql Forge.
#           Generates username and password for the
#           new Postgresql environment.

safe gen 16 ${CREDENTIALS}/postgresql username
safe gen       ${CREDENTIALS}/postgresql password

exit 0
