---
meta:
  size: default
  service:
    username: (( vault $CREDENTIALS "/postgresql:username" ))
    password: (( vault $CREDENTIALS "/postgresql:password" ))
    port: 5432
  users:
  - username: (( grab meta.service.username ))
    password: (( grab meta.service.password ))
  hba:
  - host all all 0.0.0.0/0 md5
  - host all all ::/0 md5

releases:
  - name: postgres
    version: 2.0.0
    url: https://github.com/cloudfoundry-community/postgres-boshrelease/releases/download/v2.0.0/postgres-2.0.0.tgz
    sha1: dea5cad517c62afaf97a1b31df41ad691928d960

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: postgresql
    instances: 1
    azs: [z1]
    networks:
      - name: postgresql-service
    stemcell: default

    vm_type: (( grab meta.size ))
    persistent_disk_type: default

    jobs:
      - name:    postgres
        release: postgres
        consumes:
          db: {from: postgres}
        provides:
          db: {as: postgres}
        properties:
          postgres:
            config:
              listen_addresses: 0.0.0.0
              port: (( grab meta.service.port ))
            hba:   (( grab meta.hba ))
          pgpool:
            users: (( grab meta.users ))
