#!/bin/bash

# init - Bootstrap Script for Postgresql Forge.
#           Generates username and password for the
#           new Redis environment.

safe gen ${CREDENTIALS}/postgresql username
safe gen ${CREDENTIALS}/postgresql password
