name: postgresql-forge-ci

instance_groups:
- name: postgresql-forge
  instances: 1
  azs:       [z1]
  vm_type:   default
  stemcell:  default
  networks:
    - name: default
  jobs:
    - name: postgresql-blacksmith-plans
      release: postgresql-forge
      properties:
        plans:
          standalone:
            name: standalone
            description: A single example server, with no redundancy or replication
            limit: 7
            type: standalone
            vm_type: default

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

releases:
- name: postgresql-forge
  version: latest
